# Project: MFIT
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -L"C:/Arquivos de Programas/OpenCV/bin" -L"C:/Arquivos de Programas/OpenCV/lib" "../../../../../../Arquivos de Programas/OpenCV/lib/ml.lib" "../../../../../../Arquivos de Programas/OpenCV/lib/cv.lib" "../../../../../../Arquivos de Programas/OpenCV/lib/cvaux.lib" "../../../../../../Arquivos de Programas/OpenCV/lib/cvcam.lib" "../../../../../../Arquivos de Programas/OpenCV/lib/cxcore.lib" "../../../../../../Arquivos de Programas/OpenCV/lib/highgui.lib"  -g3 
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Arquivos de Programas/OpenCV/cv/include"  -I"C:/Arquivos de Programas/OpenCV/cvaux/include"  -I"C:/Arquivos de Programas/OpenCV/cxcore/include"  -I"C:/Arquivos de Programas/OpenCV/otherlibs/highgui" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Arquivos de Programas/OpenCV/cv/include"  -I"C:/Arquivos de Programas/OpenCV/cvaux/include"  -I"C:/Arquivos de Programas/OpenCV/cxcore/include"  -I"C:/Arquivos de Programas/OpenCV/otherlibs/highgui" 
BIN  = MFIT.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before MFIT.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "MFIT.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
