# Project: PSRVE
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = psrMainVE.o psrCam.o $(RES)
LINKOBJ  = psrMainVE.o psrCam.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" "../../../../Arquivos de programas/OpenCV/lib/ml.lib" "../../../../Arquivos de programas/OpenCV/lib/cv.lib" "../../../../Arquivos de programas/OpenCV/lib/cvaux.lib" "../../../../Arquivos de programas/OpenCV/lib/cvcam.lib" "../../../../Arquivos de programas/OpenCV/lib/cxcore.lib" "../../../../Arquivos de programas/OpenCV/lib/highgui.lib"  
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Arquivos de programas/OpenCV/cv/include"  -I"C:/Arquivos de programas/OpenCV/cvaux/include"  -I"C:/Arquivos de programas/OpenCV/cxcore/include"  -I"C:/Arquivos de programas/OpenCV/ml/include"  -I"C:/Arquivos de programas/OpenCV/otherlibs/cvcam/include"  -I"C:/Arquivos de programas/OpenCV/otherlibs/highgui" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Arquivos de programas/OpenCV/cv/include"  -I"C:/Arquivos de programas/OpenCV/cvaux/include"  -I"C:/Arquivos de programas/OpenCV/cxcore/include"  -I"C:/Arquivos de programas/OpenCV/ml/include"  -I"C:/Arquivos de programas/OpenCV/otherlibs/cvcam/include"  -I"C:/Arquivos de programas/OpenCV/otherlibs/highgui" 
BIN  = PSRVE.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before PSRVE.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "PSRVE.exe" $(LIBS)

psrMainVE.o: psrMainVE.cpp
	$(CPP) -c psrMainVE.cpp -o psrMainVE.o $(CXXFLAGS)

psrCam.o: psrCam.cpp
	$(CPP) -c psrCam.cpp -o psrCam.o $(CXXFLAGS)
